### ISSUE TITLE
Missing setup.py?

### ISSUE THREAD

**Issue by wx-b** [yzhao062/MetaOD#1]
It appears that installation can't be completed due to a missing setup.py file. Will that be added soon?

**Comment by yzhao062** [comment]
yeah it is not uploded yet. should be there this week. will post again here.

**Comment by wx-b** [comment]
Great, thanks - I will check back. Sorry to jump the gun!

**Comment by yzhao062** [comment]
It is up now. Thanks for checking up in the first place :) Cheers~
